from __future__ import annotations

from dataclasses import dataclass


MODEL_TOTALSEGMENTATOR = "totalsegmentator"
MODEL_TOTALSEG_HEAD_GLANDS = "totalseg_head_glands_cavities"
MODEL_TOTALSEG_HEAD_MUSCLES = "totalseg_head_muscles"
MODEL_TOTALSEG_HEADNECK_BONES = "totalseg_headneck_bones_vessels"
MODEL_TOTALSEG_HEADNECK_MUSCLES = "totalseg_headneck_muscles"
MODEL_TOTALSEG_BRAIN = "totalseg_brain_structures"
MODEL_TOTALSEG_LUNG_VESSELS = "totalseg_lung_vessels"
MODEL_TOTALSEG_TRUNK_CAVITIES = "totalseg_trunk_cavities"
MODEL_TOTALSEG_LIVER_SEGMENTS = "totalseg_liver_segments"
MODEL_TOTALSEG_CRANIOFACIAL = "totalseg_craniofacial_structures"
MODEL_MONAI_UNEST = "monai_unest"
MODEL_NNUNET_PELVIS = "nnunet_pelvis"

# Mapeo de constante de modelo -> task_name de TotalSegmentator
TOTALSEG_TASK_MAP: dict[str, str] = {
    MODEL_TOTALSEGMENTATOR:          "total",
    MODEL_TOTALSEG_HEAD_GLANDS:      "head_glands_cavities",
    MODEL_TOTALSEG_HEAD_MUSCLES:     "head_muscles",
    MODEL_TOTALSEG_HEADNECK_BONES:   "headneck_bones_vessels",
    MODEL_TOTALSEG_HEADNECK_MUSCLES: "headneck_muscles",
    MODEL_TOTALSEG_BRAIN:            "brain_structures",
    MODEL_TOTALSEG_LUNG_VESSELS:     "lung_vessels",
    MODEL_TOTALSEG_TRUNK_CAVITIES:   "trunk_cavities",
    MODEL_TOTALSEG_LIVER_SEGMENTS:   "liver_segments",
    MODEL_TOTALSEG_CRANIOFACIAL:     "craniofacial_structures",
}


@dataclass(frozen=True)
class StructureDefinition:
    request_key: str
    display_name: str
    clinical_name: str
    model: str
    roi_names: tuple[str, ...]
    color: tuple[int, int, int]


RIGHT_LUNG_ROIS = (
    "lung_upper_lobe_right",
    "lung_middle_lobe_right",
    "lung_lower_lobe_right",
)

LEFT_LUNG_ROIS = (
    "lung_upper_lobe_left",
    "lung_lower_lobe_left",
)

VERTEBRAE_ROIS = (
    "vertebrae_C1",
    "vertebrae_C2",
    "vertebrae_C3",
    "vertebrae_C4",
    "vertebrae_C5",
    "vertebrae_C6",
    "vertebrae_C7",
    "vertebrae_T1",
    "vertebrae_T2",
    "vertebrae_T3",
    "vertebrae_T4",
    "vertebrae_T5",
    "vertebrae_T6",
    "vertebrae_T7",
    "vertebrae_T8",
    "vertebrae_T9",
    "vertebrae_T10",
    "vertebrae_T11",
    "vertebrae_T12",
    "vertebrae_L1",
    "vertebrae_L2",
    "vertebrae_L3",
    "vertebrae_L4",
    "vertebrae_L5",
)

PELVIS_BONE_ROIS = (
    "hip_left",
    "hip_right",
    "sacrum",
)

FEMUR_ROIS = (
    "femur_left",
    "femur_right",
)

RIB_ROIS = tuple(
    [f"rib_left_{index}" for index in range(1, 13)]
    + [f"rib_right_{index}" for index in range(1, 13)]
)


STRUCTURES: dict[str, StructureDefinition] = {
    "liver": StructureDefinition(
        request_key="liver",
        display_name="Higado",
        clinical_name="Liver",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("liver",),
        color=(0, 102, 204),
    ),
    "spleen": StructureDefinition(
        request_key="spleen",
        display_name="Bazo",
        clinical_name="Spleen",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("spleen",),
        color=(0, 153, 255),
    ),
    "kidney_right": StructureDefinition(
        request_key="kidney_right",
        display_name="Rinon derecho",
        clinical_name="Kidney_R",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("kidney_right",),
        color=(51, 153, 255),
    ),
    "kidney_left": StructureDefinition(
        request_key="kidney_left",
        display_name="Rinon izquierdo",
        clinical_name="Kidney_L",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("kidney_left",),
        color=(102, 178, 255),
    ),
    "pancreas": StructureDefinition(
        request_key="pancreas",
        display_name="Pancreas",
        clinical_name="Pancreas",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("pancreas",),
        color=(0, 128, 255),
    ),
    "gallbladder": StructureDefinition(
        request_key="gallbladder",
        display_name="Vesicula biliar",
        clinical_name="Gallbladder",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("gallbladder",),
        color=(0, 204, 204),
    ),
    "aorta_abdominal": StructureDefinition(
        request_key="aorta_abdominal",
        display_name="Aorta abdominal",
        clinical_name="Aorta",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("aorta",),
        color=(255, 64, 64),
    ),
    "stomach": StructureDefinition(
        request_key="stomach",
        display_name="Estomago",
        clinical_name="Stomach",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("stomach",),
        color=(255, 153, 51),
    ),
    "intestine": StructureDefinition(
        request_key="intestine",
        display_name="Intestino",
        clinical_name="Bowel",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("small_bowel", "colon"),
        color=(255, 204, 0),
    ),
    "lung_right": StructureDefinition(
        request_key="lung_right",
        display_name="Pulmon derecho",
        clinical_name="Lung_R",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=RIGHT_LUNG_ROIS,
        color=(102, 204, 255),
    ),
    "lung_left": StructureDefinition(
        request_key="lung_left",
        display_name="Pulmon izquierdo",
        clinical_name="Lung_L",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=LEFT_LUNG_ROIS,
        color=(51, 153, 204),
    ),
    "heart": StructureDefinition(
        request_key="heart",
        display_name="Corazon",
        clinical_name="Heart",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("heart",),
        color=(255, 80, 80),
    ),
    "trachea": StructureDefinition(
        request_key="trachea",
        display_name="Traquea",
        clinical_name="Trachea",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("trachea",),
        color=(102, 255, 204),
    ),
    "esophagus": StructureDefinition(
        request_key="esophagus",
        display_name="Esofago",
        clinical_name="Esophagus",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("esophagus",),
        color=(255, 170, 102),
    ),
    "vertebrae": StructureDefinition(
        request_key="vertebrae",
        display_name="Vertebras",
        clinical_name="Vertebrae",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=VERTEBRAE_ROIS,
        color=(210, 180, 140),
    ),
    "pelvis_bone": StructureDefinition(
        request_key="pelvis_bone",
        display_name="Pelvis osea",
        clinical_name="Pelvis_Bone",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=PELVIS_BONE_ROIS,
        color=(196, 164, 132),
    ),
    "femurs": StructureDefinition(
        request_key="femurs",
        display_name="Femures",
        clinical_name="Femurs",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=FEMUR_ROIS,
        color=(184, 134, 11),
    ),
    "ribs": StructureDefinition(
        request_key="ribs",
        display_name="Costillas",
        clinical_name="Ribs",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=RIB_ROIS,
        color=(222, 184, 135),
    ),
    "brain": StructureDefinition(
        request_key="brain",
        display_name="Cerebro completo",
        clinical_name="Brain",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("brain",),
        color=(204, 102, 255),
    ),
    "prostate": StructureDefinition(
        request_key="prostate",
        display_name="Prostata",
        clinical_name="Prostate",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("prostate",),
        color=(255, 153, 153),
    ),
    "bladder": StructureDefinition(
        request_key="bladder",
        display_name="Vejiga",
        clinical_name="Bladder",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("urinary_bladder",),
        color=(255, 230, 128),
    ),
    "penile_bulb": StructureDefinition(
        request_key="penile_bulb",
        display_name="Bulbo peneano",
        clinical_name="PenileBulb",
        model=MODEL_NNUNET_PELVIS,
        roi_names=(),
        color=(255, 102, 102),
    ),
    "lymph_nodes_pelvis": StructureDefinition(
        request_key="lymph_nodes_pelvis",
        display_name="Ganglios pelvicos",
        clinical_name="PelvicLymphNodes",
        model=MODEL_NNUNET_PELVIS,
        roi_names=(),
        color=(255, 204, 153),
    ),
    # ── Médula espinal (total task) ──────────────────────────────────────
    "spinal_cord": StructureDefinition(
        request_key="spinal_cord",
        display_name="Medula espinal",
        clinical_name="SpinalCord",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("spinal_cord",),
        color=(255, 255, 153),
    ),
    # ── Total task — estructuras adicionales ─────────────────────────────
    "duodenum": StructureDefinition(
        request_key="duodenum",
        display_name="Duodeno",
        clinical_name="Duodenum",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("duodenum",),
        color=(255, 220, 100),
    ),
    "adrenal_right": StructureDefinition(
        request_key="adrenal_right",
        display_name="Suprarrenal derecha",
        clinical_name="Adrenal_R",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("adrenal_gland_right",),
        color=(200, 200, 100),
    ),
    "adrenal_left": StructureDefinition(
        request_key="adrenal_left",
        display_name="Suprarrenal izquierda",
        clinical_name="Adrenal_L",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("adrenal_gland_left",),
        color=(220, 220, 110),
    ),
    "pulmonary_vein": StructureDefinition(
        request_key="pulmonary_vein",
        display_name="Venas pulmonares",
        clinical_name="V_Pulmonary",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("pulmonary_vein",),
        color=(150, 200, 255),
    ),
    "vena_cava_sup": StructureDefinition(
        request_key="vena_cava_sup",
        display_name="Vena cava superior",
        clinical_name="V_Cava_Sup",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("superior_vena_cava",),
        color=(100, 150, 255),
    ),
    "vena_cava_inf": StructureDefinition(
        request_key="vena_cava_inf",
        display_name="Vena cava inferior",
        clinical_name="V_Cava_Inf",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("inferior_vena_cava",),
        color=(80, 130, 255),
    ),
    "portal_vein": StructureDefinition(
        request_key="portal_vein",
        display_name="Vena porta y esplenica",
        clinical_name="V_Portal",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("portal_vein_and_splenic_vein",),
        color=(120, 160, 200),
    ),
    "iliac_artery_left": StructureDefinition(
        request_key="iliac_artery_left",
        display_name="Arteria iliaca izquierda",
        clinical_name="A_Iliac_L",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("iliac_artery_left",),
        color=(255, 80, 80),
    ),
    "iliac_artery_right": StructureDefinition(
        request_key="iliac_artery_right",
        display_name="Arteria iliaca derecha",
        clinical_name="A_Iliac_R",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("iliac_artery_right",),
        color=(255, 100, 100),
    ),
    "iliac_vein_left": StructureDefinition(
        request_key="iliac_vein_left",
        display_name="Vena iliaca izquierda",
        clinical_name="V_Iliac_L",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("iliac_vena_left",),
        color=(100, 160, 240),
    ),
    "iliac_vein_right": StructureDefinition(
        request_key="iliac_vein_right",
        display_name="Vena iliaca derecha",
        clinical_name="V_Iliac_R",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("iliac_vena_right",),
        color=(120, 180, 250),
    ),
    "skull": StructureDefinition(
        request_key="skull",
        display_name="Craneo",
        clinical_name="Skull",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("skull",),
        color=(220, 200, 170),
    ),
    "uterus": StructureDefinition(
        request_key="uterus",
        display_name="Utero",
        clinical_name="Uterus",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("uterus",),
        color=(255, 100, 150),
    ),
    "thymus": StructureDefinition(
        request_key="thymus",
        display_name="Timo",
        clinical_name="Thymus",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("thymus",),
        color=(180, 255, 200),
    ),
    "clavicle_left": StructureDefinition(
        request_key="clavicle_left",
        display_name="Clavicula izquierda",
        clinical_name="Clavicle_L",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("clavicula_left",),
        color=(220, 190, 150),
    ),
    "clavicle_right": StructureDefinition(
        request_key="clavicle_right",
        display_name="Clavicula derecha",
        clinical_name="Clavicle_R",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("clavicula_right",),
        color=(230, 200, 160),
    ),
    "humerus_left": StructureDefinition(
        request_key="humerus_left",
        display_name="Humero izquierdo",
        clinical_name="HumeralHead_L",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("humerus_left",),
        color=(210, 185, 145),
    ),
    "humerus_right": StructureDefinition(
        request_key="humerus_right",
        display_name="Humero derecho",
        clinical_name="HumeralHead_R",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("humerus_right",),
        color=(220, 195, 155),
    ),
    "thyroid_gland": StructureDefinition(
        request_key="thyroid_gland",
        display_name="Glandula tiroides",
        clinical_name="Thyroid",
        model=MODEL_TOTALSEGMENTATOR,
        roi_names=("thyroid_gland",),
        color=(150, 220, 180),
    ),
    # ── head_glands_cavities — estructuras adicionales ───────────────────
    "nasal_cavity_right": StructureDefinition(
        request_key="nasal_cavity_right",
        display_name="Fosa nasal derecha",
        clinical_name="NasalCavity_R",
        model=MODEL_TOTALSEG_HEAD_GLANDS,
        roi_names=("nasal_cavity_right",),
        color=(200, 240, 255),
    ),
    "nasal_cavity_left": StructureDefinition(
        request_key="nasal_cavity_left",
        display_name="Fosa nasal izquierda",
        clinical_name="NasalCavity_L",
        model=MODEL_TOTALSEG_HEAD_GLANDS,
        roi_names=("nasal_cavity_left",),
        color=(210, 245, 255),
    ),
    "auditory_canal_right": StructureDefinition(
        request_key="auditory_canal_right",
        display_name="Conducto auditivo derecho",
        clinical_name="AudCanal_R",
        model=MODEL_TOTALSEG_HEAD_GLANDS,
        roi_names=("auditory_canal_right",),
        color=(100, 200, 200),
    ),
    "auditory_canal_left": StructureDefinition(
        request_key="auditory_canal_left",
        display_name="Conducto auditivo izquierdo",
        clinical_name="AudCanal_L",
        model=MODEL_TOTALSEG_HEAD_GLANDS,
        roi_names=("auditory_canal_left",),
        color=(120, 210, 210),
    ),
    "soft_palate": StructureDefinition(
        request_key="soft_palate",
        display_name="Paladar blando",
        clinical_name="Palate_Soft",
        model=MODEL_TOTALSEG_HEAD_GLANDS,
        roi_names=("soft_palate",),
        color=(255, 180, 160),
    ),
    "hard_palate": StructureDefinition(
        request_key="hard_palate",
        display_name="Paladar duro",
        clinical_name="Palate_Hard",
        model=MODEL_TOTALSEG_HEAD_GLANDS,
        roi_names=("hard_palate",),
        color=(240, 200, 180),
    ),
    # ── headneck_bones_vessels — estructuras adicionales ─────────────────
    "hyoid": StructureDefinition(
        request_key="hyoid",
        display_name="Hioides",
        clinical_name="Hyoid",
        model=MODEL_TOTALSEG_HEADNECK_BONES,
        roi_names=("hyoid",),
        color=(190, 210, 230),
    ),
    "cricoid_cartilage": StructureDefinition(
        request_key="cricoid_cartilage",
        display_name="Cartilago cricoides",
        clinical_name="Cricoid",
        model=MODEL_TOTALSEG_HEADNECK_BONES,
        roi_names=("cricoid_cartilage",),
        color=(178, 216, 255),
    ),
    "zygomatic_arch_right": StructureDefinition(
        request_key="zygomatic_arch_right",
        display_name="Arco cigomatico derecho",
        clinical_name="ZygArch_R",
        model=MODEL_TOTALSEG_HEADNECK_BONES,
        roi_names=("zygomatic_arch_right",),
        color=(210, 195, 175),
    ),
    "zygomatic_arch_left": StructureDefinition(
        request_key="zygomatic_arch_left",
        display_name="Arco cigomatico izquierdo",
        clinical_name="ZygArch_L",
        model=MODEL_TOTALSEG_HEADNECK_BONES,
        roi_names=("zygomatic_arch_left",),
        color=(215, 200, 180),
    ),
    "carotid_right": StructureDefinition(
        request_key="carotid_right",
        display_name="Arteria carotida interna derecha",
        clinical_name="A_Carotid_R",
        model=MODEL_TOTALSEG_HEADNECK_BONES,
        roi_names=("internal_carotid_artery_right",),
        color=(255, 70, 70),
    ),
    "carotid_left": StructureDefinition(
        request_key="carotid_left",
        display_name="Arteria carotida interna izquierda",
        clinical_name="A_Carotid_L",
        model=MODEL_TOTALSEG_HEADNECK_BONES,
        roi_names=("internal_carotid_artery_left",),
        color=(255, 90, 90),
    ),
    "jugular_right": StructureDefinition(
        request_key="jugular_right",
        display_name="Vena yugular interna derecha",
        clinical_name="V_Jugular_R",
        model=MODEL_TOTALSEG_HEADNECK_BONES,
        roi_names=("internal_jugular_vein_right",),
        color=(90, 150, 230),
    ),
    "jugular_left": StructureDefinition(
        request_key="jugular_left",
        display_name="Vena yugular interna izquierda",
        clinical_name="V_Jugular_L",
        model=MODEL_TOTALSEG_HEADNECK_BONES,
        roi_names=("internal_jugular_vein_left",),
        color=(110, 165, 240),
    ),
    # ── headneck_muscles — estructuras adicionales ───────────────────────
    "platysma_right": StructureDefinition(
        request_key="platysma_right",
        display_name="Platisma derecho",
        clinical_name="Musc_Platysma_R",
        model=MODEL_TOTALSEG_HEADNECK_MUSCLES,
        roi_names=("platysma_right",),
        color=(180, 220, 180),
    ),
    "platysma_left": StructureDefinition(
        request_key="platysma_left",
        display_name="Platisma izquierdo",
        clinical_name="Musc_Platysma_L",
        model=MODEL_TOTALSEG_HEADNECK_MUSCLES,
        roi_names=("platysma_left",),
        color=(190, 230, 190),
    ),
    "trapezius_hn_right": StructureDefinition(
        request_key="trapezius_hn_right",
        display_name="Trapecio cuello derecho",
        clinical_name="Musc_Trapezius_R",
        model=MODEL_TOTALSEG_HEADNECK_MUSCLES,
        roi_names=("trapezius_right",),
        color=(160, 210, 160),
    ),
    "trapezius_hn_left": StructureDefinition(
        request_key="trapezius_hn_left",
        display_name="Trapecio cuello izquierdo",
        clinical_name="Musc_Trapezius_L",
        model=MODEL_TOTALSEG_HEADNECK_MUSCLES,
        roi_names=("trapezius_left",),
        color=(170, 215, 170),
    ),
    # ── head_muscles — estructuras adicionales ───────────────────────────
    "temporalis_right": StructureDefinition(
        request_key="temporalis_right",
        display_name="Temporal derecho",
        clinical_name="Musc_Temporalis_R",
        model=MODEL_TOTALSEG_HEAD_MUSCLES,
        roi_names=("temporalis_right",),
        color=(255, 120, 160),
    ),
    "temporalis_left": StructureDefinition(
        request_key="temporalis_left",
        display_name="Temporal izquierdo",
        clinical_name="Musc_Temporalis_L",
        model=MODEL_TOTALSEG_HEAD_MUSCLES,
        roi_names=("temporalis_left",),
        color=(255, 130, 170),
    ),
    "lat_pterygoid_right": StructureDefinition(
        request_key="lat_pterygoid_right",
        display_name="Pterigoideo lateral derecho",
        clinical_name="Musc_LPterygoid_R",
        model=MODEL_TOTALSEG_HEAD_MUSCLES,
        roi_names=("lateral_pterygoid_right",),
        color=(200, 100, 150),
    ),
    "lat_pterygoid_left": StructureDefinition(
        request_key="lat_pterygoid_left",
        display_name="Pterigoideo lateral izquierdo",
        clinical_name="Musc_LPterygoid_L",
        model=MODEL_TOTALSEG_HEAD_MUSCLES,
        roi_names=("lateral_pterygoid_left",),
        color=(210, 110, 160),
    ),
    "med_pterygoid_right": StructureDefinition(
        request_key="med_pterygoid_right",
        display_name="Pterigoideo medial derecho",
        clinical_name="Musc_MPterygoid_R",
        model=MODEL_TOTALSEG_HEAD_MUSCLES,
        roi_names=("medial_pterygoid_right",),
        color=(185, 90, 140),
    ),
    "med_pterygoid_left": StructureDefinition(
        request_key="med_pterygoid_left",
        display_name="Pterigoideo medial izquierdo",
        clinical_name="Musc_MPterygoid_L",
        model=MODEL_TOTALSEG_HEAD_MUSCLES,
        roi_names=("medial_pterygoid_left",),
        color=(195, 100, 150),
    ),
    "digastric_right": StructureDefinition(
        request_key="digastric_right",
        display_name="Digastrico derecho",
        clinical_name="Musc_Digastric_R",
        model=MODEL_TOTALSEG_HEAD_MUSCLES,
        roi_names=("digastric_right",),
        color=(170, 210, 200),
    ),
    "digastric_left": StructureDefinition(
        request_key="digastric_left",
        display_name="Digastrico izquierdo",
        clinical_name="Musc_Digastric_L",
        model=MODEL_TOTALSEG_HEAD_MUSCLES,
        roi_names=("digastric_left",),
        color=(180, 215, 205),
    ),
    # ── brain_structures — estructuras adicionales ───────────────────────
    "brainstem": StructureDefinition(
        request_key="brainstem",
        display_name="Tronco cerebral",
        clinical_name="Brainstem",
        model=MODEL_TOTALSEG_BRAIN,
        roi_names=("brainstem",),
        color=(178, 102, 204),
    ),
    "cerebellum": StructureDefinition(
        request_key="cerebellum",
        display_name="Cerebelo",
        clinical_name="Cerebellum",
        model=MODEL_TOTALSEG_BRAIN,
        roi_names=("cerebellum",),
        color=(160, 100, 210),
    ),
    "thalamus": StructureDefinition(
        request_key="thalamus",
        display_name="Talamo",
        clinical_name="Thalamus",
        model=MODEL_TOTALSEG_BRAIN,
        roi_names=("thalamus",),
        color=(190, 130, 230),
    ),
    "hippocampus": StructureDefinition(
        request_key="hippocampus",
        display_name="Hipocampo",
        clinical_name="Hippocampus",
        model=MODEL_TOTALSEG_BRAIN,
        roi_names=("hippocampus",),
        color=(180, 80, 180),
    ),
    "ventricle": StructureDefinition(
        request_key="ventricle",
        display_name="Ventriculos cerebrales",
        clinical_name="Ventricle",
        model=MODEL_TOTALSEG_BRAIN,
        roi_names=("ventricle",),
        color=(220, 180, 255),
    ),
    # ── lung_vessels (Apache-2.0) ────────────────────────────────────────
    "lung_vessels": StructureDefinition(
        request_key="lung_vessels",
        display_name="Vasos pulmonares",
        clinical_name="LungVessels",
        model=MODEL_TOTALSEG_LUNG_VESSELS,
        roi_names=("lung_vessels",),
        color=(150, 200, 255),
    ),
    "lung_bronchia": StructureDefinition(
        request_key="lung_bronchia",
        display_name="Arbol bronquial",
        clinical_name="Bronchia",
        model=MODEL_TOTALSEG_LUNG_VESSELS,
        roi_names=("lung_trachea_bronchia",),
        color=(102, 255, 204),
    ),
    # ── trunk_cavities (Apache-2.0) ──────────────────────────────────────
    "thoracic_cavity": StructureDefinition(
        request_key="thoracic_cavity",
        display_name="Cavidad toracica",
        clinical_name="CavityThoracic",
        model=MODEL_TOTALSEG_TRUNK_CAVITIES,
        roi_names=("thoracic_cavity",),
        color=(200, 230, 255),
    ),
    "abdominal_cavity": StructureDefinition(
        request_key="abdominal_cavity",
        display_name="Cavidad abdominal",
        clinical_name="CavityAbdom",
        model=MODEL_TOTALSEG_TRUNK_CAVITIES,
        roi_names=("abdominal_cavity",),
        color=(255, 240, 200),
    ),
    "pericardium": StructureDefinition(
        request_key="pericardium",
        display_name="Pericardio",
        clinical_name="Pericardium",
        model=MODEL_TOTALSEG_TRUNK_CAVITIES,
        roi_names=("pericardium",),
        color=(255, 120, 80),
    ),
    "mediastinum": StructureDefinition(
        request_key="mediastinum",
        display_name="Mediastino",
        clinical_name="Mediastinum",
        model=MODEL_TOTALSEG_TRUNK_CAVITIES,
        roi_names=("mediastinum",),
        color=(220, 200, 240),
    ),
    # ── liver_segments (Apache-2.0, entrenado en dataset pequeño*) ───────
    "liver_seg_1": StructureDefinition(
        request_key="liver_seg_1",
        display_name="Segmento hepatico I",
        clinical_name="Liver_Seg1",
        model=MODEL_TOTALSEG_LIVER_SEGMENTS,
        roi_names=("liver_segment_1",),
        color=(20, 120, 220),
    ),
    "liver_seg_2": StructureDefinition(
        request_key="liver_seg_2",
        display_name="Segmento hepatico II",
        clinical_name="Liver_Seg2",
        model=MODEL_TOTALSEG_LIVER_SEGMENTS,
        roi_names=("liver_segment_2",),
        color=(40, 140, 230),
    ),
    "liver_seg_3": StructureDefinition(
        request_key="liver_seg_3",
        display_name="Segmento hepatico III",
        clinical_name="Liver_Seg3",
        model=MODEL_TOTALSEG_LIVER_SEGMENTS,
        roi_names=("liver_segment_3",),
        color=(60, 160, 240),
    ),
    "liver_seg_4": StructureDefinition(
        request_key="liver_seg_4",
        display_name="Segmento hepatico IV",
        clinical_name="Liver_Seg4",
        model=MODEL_TOTALSEG_LIVER_SEGMENTS,
        roi_names=("liver_segment_4",),
        color=(80, 180, 245),
    ),
    "liver_seg_5": StructureDefinition(
        request_key="liver_seg_5",
        display_name="Segmento hepatico V",
        clinical_name="Liver_Seg5",
        model=MODEL_TOTALSEG_LIVER_SEGMENTS,
        roi_names=("liver_segment_5",),
        color=(100, 190, 248),
    ),
    "liver_seg_6": StructureDefinition(
        request_key="liver_seg_6",
        display_name="Segmento hepatico VI",
        clinical_name="Liver_Seg6",
        model=MODEL_TOTALSEG_LIVER_SEGMENTS,
        roi_names=("liver_segment_6",),
        color=(120, 200, 250),
    ),
    "liver_seg_7": StructureDefinition(
        request_key="liver_seg_7",
        display_name="Segmento hepatico VII",
        clinical_name="Liver_Seg7",
        model=MODEL_TOTALSEG_LIVER_SEGMENTS,
        roi_names=("liver_segment_7",),
        color=(140, 210, 252),
    ),
    "liver_seg_8": StructureDefinition(
        request_key="liver_seg_8",
        display_name="Segmento hepatico VIII",
        clinical_name="Liver_Seg8",
        model=MODEL_TOTALSEG_LIVER_SEGMENTS,
        roi_names=("liver_segment_8",),
        color=(160, 220, 254),
    ),
    # ── craniofacial_structures (Apache-2.0) ─────────────────────────────
    "mandible": StructureDefinition(
        request_key="mandible",
        display_name="Mandibula",
        clinical_name="Mandible",
        model=MODEL_TOTALSEG_CRANIOFACIAL,
        roi_names=("mandible",),
        color=(200, 180, 140),
    ),
}


MODEL_LABELS = {
    MODEL_TOTALSEGMENTATOR:          "TotalSegmentator V2",
    MODEL_TOTALSEG_HEAD_GLANDS:      "TotalSegmentator V2 (Head Glands)",
    MODEL_TOTALSEG_HEAD_MUSCLES:     "TotalSegmentator V2 (Head Muscles)",
    MODEL_TOTALSEG_HEADNECK_BONES:   "TotalSegmentator V2 (HeadNeck Bones)",
    MODEL_TOTALSEG_HEADNECK_MUSCLES: "TotalSegmentator V2 (HeadNeck Muscles)",
    MODEL_TOTALSEG_BRAIN:            "TotalSegmentator V2 (Brain)",
    MODEL_TOTALSEG_LUNG_VESSELS:     "TotalSegmentator V2 (Lung Vessels)",
    MODEL_TOTALSEG_TRUNK_CAVITIES:   "TotalSegmentator V2 (Trunk Cavities)",
    MODEL_TOTALSEG_LIVER_SEGMENTS:   "TotalSegmentator V2 (Liver Segments)",
    MODEL_TOTALSEG_CRANIOFACIAL:     "TotalSegmentator V2 (Craniofacial)",
    MODEL_MONAI_UNEST:               "MONAI UNesT",
    MODEL_NNUNET_PELVIS:             "nnU-Net Pelvis",
}


MVP_STRUCTURE_KEYS = (
    "liver",
    "spleen",
    "kidney_right",
    "kidney_left",
    "pancreas",
)
